# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane
default_platform(:android)

platform :android do
  desc "Déploiement sur le Play Store - track internal"
  lane :release do
    build_android_app(
      keystore_path: "app/key.jks",
      keystore_password: ENV["KEYSTORE_PASSWORD"],
      key_alias: ENV["KEY_ALIAS"],
      key_password: ENV["KEY_PASSWORD"]
    )
    upload_to_play_store(
      track: "internal",
      json_key: "fastlane/service-account.json"
    )
  end
end
